substitutions:
  name: "licznik-imp-1w"
  friendly_name: "Licznik Impulsów"

esphome:
  name: "${name}"
  friendly_name: "${friendly_name}"
  name_add_mac_suffix: true
  comment: Impuls Counter + 1W by CyberIN
  min_version: "2023.2.0"
  project:
    name: CyberIN.licznik-imp-1w
    version: "1.2.7"

esp8266:
  board: d1_mini

# dashboard_import:
#   # package_import_url: github://CyberIN-pl/licznik-imp-1w/blob/main/licznik-imp-1w.yaml@main
#   # import_full_config: True
#   package_import_url: github://CyberIN-pl/licznik-imp-1w/blob/main/licznik-imp-1w.yaml@main
#   import_full_config: False  

logger:

api:
  reboot_timeout: 60min

ota:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "Licznik Impulsow"

captive_portal:

web_server:
  port: 80

dallas:
  - pin: D5   

light:
  - platform: status_led
    id: led
    pin: 
      number: D4
    internal: true

  - platform: binary
    id: red
    output: light_output
    internal: true 
    restore_mode: ALWAYS_ON   

output:
  - id: light_output
    platform: gpio
    pin: D6    
      # inverted: true

binary_sensor:
  - platform: gpio
    pin: 
      number: D2
      inverted: true
    internal: true
    id: impuls
    on_press:
      then:
        - light.turn_on: red
    on_release:
      then:
        - light.turn_off: red
   

sensor:

  - platform: wifi_signal
    name: "${name} -  Sygnał Wifi"
    update_interval: 900s 

  - platform: dallas
    # address: 0x1f03009779d36328
    index: 0
    name: "${name} - T1"      
  - platform: dallas
    # address: 0x6b03009779f5fb28
    index: 1
    name: "${name} - T2"   

  - platform: pulse_counter
    id: pc
    pin:
      number: D2
      mode: INPUT_PULLUP
      inverted: True  
    unit_of_measurement: 'W'
    accuracy_decimals: 0    
    name: "${name} - Moc Chwilowa"
    device_class: power
    update_interval: 60s
    filters:
      - debounce: 100ms
      - multiply: 60  #(60s/1000 pulses -> kWh) * 1000 -> W
    total:
      name: "${name} - Energia"

      unit_of_measurement: 'kWh'
      device_class: energy 
      state_class: total_increasing
      accuracy_decimals: 3
      icon: "mdi:pulse"   
      filters:
        - multiply: 0.001  # (1/1000 pulses per kWh) 
    
