substitutions:
  name: testimport
  friendly_name: testimport

esphome:
  name: "${name}"
  friendly_name: "${friendly_name}"
  name_add_mac_suffix: true
  project:
    name: esphome.project-template
    version: "1.0"  

esp8266:
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

dashboard_import:
  package_import_url: github://CyberIN-pl/licznik-imp-1w/blob/main/licznik-imp-1w.yaml@main
  import_full_config: false # or true


wifi:
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:

captive_portal:
